void Thank_You();
void d_line();
void Wel_Come();
void _sound();
void Display_Menue();
void Display_Teacher_Menue();
void Display_Student_Menue();


#define P cout<<


void Display_Menue()
{
	
	system("CLS");
	cout<<"\n\n\n\t\t\tC++ MICROPROJECT ON QUIZ GAME\n\n";
	cout<<"\t\tÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·"<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º"<<endl;
	cout<<"\t\tº  Û           WELCOME TO QUIZ GAME         Û º"<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º"<<endl;
	cout<<"\t\tº  Û   1.] Teacher Login.                   Û º"<<endl;
	cout<<"\t\tº  Û                                        Û º"<<endl;
	cout<<"\t\tº  Û   2.] Student Login.                   Û º"<<endl;
	cout<<"\t\tº  Û                                        Û º"<<endl;
	cout<<"\t\tº  Û   3.] EXIT.                            Û º"<<endl;
	cout<<"\t\tº  Û                                        Û º"<<endl;
	cout<<"\t\tº  ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½"<<endl;

}
void Display_Teacher_Menue()
{
	system("CLS");
	cout<<"\n\n\n\t\t\tC++ MICROPROJECT ON QUIZ GAME\n\n";
	cout<<"\t\tÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ· "<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º  "<<endl;
	cout<<"\t\tº  Û              TEACHER LOGIN		    Û º  "<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º  "<<endl;
	cout<<"\t\tº  Û   1.] ADD NEW QUESTION.		    Û º  "<<endl;
	cout<<"\t\tº  Û 					    Û º	 "<<endl;
	cout<<"\t\tº  Û   2.] SEE PREVIOUS ENTERED QUESTIONS.  Û º	 "<<endl;
	cout<<"\t\tº  Û   					    Û º	 "<<endl;
	cout<<"\t\tº  Û   3.] MAIN MENU. 			    Û º	 "<<endl;
	cout<<"\t\tº  Û 					    Û º"<<endl;
	cout<<"\t\tº  ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß º	 "<<endl;
	cout<<"\t\tº   					      º"<<endl;
	cout<<"\t\tº   					      º"<<endl;
	cout<<"\t\tº   					      º"<<endl;
	cout<<"\t\tÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½  "<<endl;
}

void Display_Student_Menue()
{
	system("CLS");
	cout<<"\n\n\n\t\t\tC++ MICROPROJECT ON QUIZ GAME\n\n";
	cout<<"\t\tÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·"<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º"<<endl;
	cout<<"\t\tº  Û           STUDENT LOGIN                Û º"<<endl;
	cout<<"\t\tº  ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ º"<<endl;
	cout<<"\t\tº  Û   1.] PRACTISE MODE.                   Û º"<<endl;
	cout<<"\t\tº  Û 					    Û º"<<endl;
	cout<<"\t\tº  Û   2.] TEST MODE.			    Û º"<<endl;
	cout<<"\t\tº  Û 					    Û º"<<endl;
	cout<<"\t\tº  Û   3.] MAIN MENUE			    Û º"<<endl;
	cout<<"\t\tº  Û 					    Û º"<<endl;
	cout<<"\t\tº  ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tº                                             º"<<endl;
	cout<<"\t\tÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½"<<endl;
}


void Thank_You()
{
	cout<<"\n\n";
	d_line();
	P "\t\t\t\tThank You...!!!\n";
    d_line();
	P "\t\t\tDesign and develop by the team\n";
	d_line();
	P "\n\t\t\tRaj Gandole\t\t18CM048";
	P "\n\n\t\t\tRaghav Rathi\t\t18CM049";
	P "\n\n\t\t\tVedanti Raut\t\t18CM050";
	P "\n\n\t\t\tSadiya Abdul Salim\t18CM051";
	P "\n\n\t\t\tSiddesh Sambe\t\t18CM052\n\n";
	d_line();

	P "\t\t\tMade using C++\n";
	P "\t\t\tCollege :- Goverment Polytecnic , Amravati\n";

	d_line();
	P "\t\t\t\t\t- Under Guidence of \" Pravin Satav Sir \"";


    d_line();

    getch();
}
void d_line()
{
//     P"ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ";
       P"================================================================================";
}
void Wel_Come()
{
    /* will print WELCOME */
	P"\t  [ .W."; _sound();
    P"E."; _sound();
    P"L."; _sound();
    P"C."; _sound();
    P"O."; _sound();
	P"M."; _sound();
    P"E."; _sound();

    /* will print TO */

    P" .T."; _sound();
    P"O.";    _sound();

    /* will print QUIZ */

    P" .Q."; _sound();
    P"U."; _sound();
    P"I."; _sound();
    P"Z."; _sound();

    /* will print COMPETITION */

	P" .C."; _sound();
    P"O."; _sound();
    P"M."; _sound();
	P"P."; _sound();
    P"E."; _sound();
    P"T."; _sound();
    P"I."; _sound();
    P"T."; _sound();
    P"I."; _sound();
    P"O."; _sound();
    P"N. ]"; _sound();
}
///*==========================================================================*
void _sound()
{
	sound(500);
	delay(50);
	nosound();
	delay(50);
}
